# Generated by Django 5.0.3 on 2024-05-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('SERVICE_ADMIN', 'Service Admin'), ('SERVICE_MANAGER', 'Service Manager'), ('FOUNDER', 'Fondateur'), ('SERVICE_STAFF', 'Service Staff'), ('ADMIN_IRE', 'Admin IRE'), ('ADMIN_DPE', 'Admin DPE'), ('ADMIN_DCE', 'Admin DCE'), ('STAFF_IRE', 'Personnel de IRE'), ('STAFF_DCE', 'Personnel de DCE'), ('STAFF_DPE', 'Personnel de DPE'), ('SCHOOL_ADMIN', 'School Admin'), ('SCHOOL_MANAGER', 'School Manager'), ('SCHOOL', 'School'), ('SCHOOL_STAFF', "Personnel d'école"), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent')], max_length=20),
        ),
    ]
