# Generated by Django 5.0.3 on 2025-07-01 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.IntegerField(choices=[(0, 'Féminin'), (1, 'Masculin')])),
                ('phone', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='founders/photos')),
                ('document', models.FileField(blank=True, null=True, upload_to='founders/documents')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('public', 'Ecole Publique'), ('private', 'Ecole Privée')], max_length=200)),
                ('category', models.IntegerField(choices=[(0, 'Enseignement primaire'), (1, 'Enseignement Seconaire')])),
                ('level', models.IntegerField(choices=[(0, 'Primaire'), (1, 'Collège'), (2, 'Lycée'), (3, 'Ecole Primaire et Collège'), (4, 'Collège et lycée'), (5, 'Tous les niveaux')])),
                ('phone', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='schools/images')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_of_education', to='service.service')),
                ('founder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.founder')),
                ('ire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[(0, 'Féminin'), (1, 'Masculin')], max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('formation', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staffs/images')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='staffs/documents')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
