# Generated by Django 5.0.3 on 2024-05-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='category',
            field=models.CharField(choices=[('primary_education', 'Enseignement primaire'), ('secondary_education', 'Enseignement Seconaire')], max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='level',
            field=models.CharField(choices=[('primary', 'Primaire'), ('college_cycle', 'Collège'), ('high_school_cycle', 'Lycée'), ('primary_college', 'Ecole Primaire et Collège'), ('college_high_school', 'Collège et lycée'), ('general_level', 'Tous les niveaux')], max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('public', 'Ecole Publique'), ('private', 'Ecole Privée')], max_length=200),
        ),
    ]
