# Generated by Django 5.0.3 on 2025-07-01 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type_service', models.CharField(choices=[('ministerial_cabinet', 'Cabinet Ministériel'), ('national_directorate', 'Direction Nationale'), ('ire', 'Inspection Régionale'), ('dpe', "Direction Préfectorale de l'Education"), ('dce', "Direction Communale de l'Education")], max_length=200)),
                ('region', models.CharField(choices=[('national', 'National'), ('boke', 'Boké'), ('conakry', 'Conakry'), ('faranah', 'Faranah'), ('kankan', 'Kankan'), ('kindia', 'Kindia'), ('labé', 'Labé'), ('mamou', 'Mamou'), ('nzerekore', "N'Zérékoré")], max_length=200)),
                ('commune', models.CharField(blank=True, max_length=200, null=True)),
                ('prefecture', models.CharField(blank=True, max_length=200, null=True)),
                ('sous_prefecture', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('phone', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('holder', 'Titulaire'), ('contractual', 'Contractuel'), ('intern', 'Stagiaire')], max_length=20)),
                ('formation', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee/photos')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='employee/certificates')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
    ]
