# Generated by Django 5.0.3 on 2024-05-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='employee_certificates'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='formation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('holder', 'Holder'), ('contractual', 'Contractual'), ('intern', 'Intern')], max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='region',
            field=models.CharField(choices=[('national', 'National'), ('Boké', 'Boké'), ('Conakry', 'Conakry'), ('Faranah', 'Faranah'), ('Kankan', 'Kankan'), ('Kindia', 'Kindia'), ('Labé', 'Labé'), ('Mamou', 'Mamou'), ("N'Zérékoré", "N'Zérékoré")], max_length=100),
        ),
    ]
